<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="OpenText Functional Testing" productVer="25.2" os="Windows 11" host="HARI_ACER"><DocLocation><![CDATA[D:\AT\CompleteWebTest]]></DocLocation></General>
<Doc rID="T1"   productName= "OpenText Functional Testing"  >
<DName><![CDATA[CompleteWebTest]]></DName>
<Res><![CDATA[Res7]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:11]]></Time>
<TimeTick>1751958491</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:12]]></Time>
<TimeTick>1751958492</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[TITAN.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:12]]></Time>
<TimeTick>1751958492</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="10" MovieMarker="MARK131" >
<Disp><![CDATA[TITAN.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf362.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="9" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf361.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="8" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf360.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Titan logo image]]></Obj>
<Details ><![CDATA[The titan logo image exists and working]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:12]]></Time>
<TimeTick>1751958492</TimeTick>
<NodeArgs eType="User" icon="8" nRep="11" status="Passed" >
<Disp><![CDATA[Titan logo image]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj ><![CDATA[Titan logo image Highlighted]]></Obj>
<Details ><![CDATA[The titan logo image got Highlighted]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:14]]></Time>
<TimeTick>1751958494</TimeTick>
<NodeArgs eType="User" icon="8" nRep="12" status="Passed" >
<Disp><![CDATA[Titan logo image Highlighted]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:14]]></Time>
<TimeTick>1751958494</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:14]]></Time>
<TimeTick>1751958494</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[TITAN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:14]]></Time>
<TimeTick>1751958494</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" MovieMarker="MARK132" >
<Disp><![CDATA[TITAN.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf365.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf364.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="14" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf363.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[Titan logo image Clicked]]></Obj>
<Details ><![CDATA[The titan logo image got Clicked]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:14]]></Time>
<TimeTick>1751958494</TimeTick>
<NodeArgs eType="User" icon="8" nRep="17" status="Passed" >
<Disp><![CDATA[Titan logo image Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:17]]></Time>
<TimeTick>1751958497</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:18]]></Time>
<TimeTick>1751958498</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Search_image.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:18]]></Time>
<TimeTick>1751958498</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" MovieMarker="MARK133" >
<Disp><![CDATA[Search_image.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf368.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf367.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="18" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf366.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Search image exists]]></Obj>
<Details ><![CDATA[The search image exists and works]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:18]]></Time>
<TimeTick>1751958498</TimeTick>
<NodeArgs eType="User" icon="8" nRep="21" status="Passed" >
<Disp><![CDATA[Search image exists]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[Search image Highlighted]]></Obj>
<Details ><![CDATA[The search image got highlighted]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:20]]></Time>
<TimeTick>1751958500</TimeTick>
<NodeArgs eType="User" icon="8" nRep="22" status="Passed" >
<Disp><![CDATA[Search image Highlighted]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:20]]></Time>
<TimeTick>1751958500</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:20]]></Time>
<TimeTick>1751958500</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA["Search_image"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (272 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Image<br>image type=Plain Image<br>html tag=IMG<br>alt=image<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (272 objects found)&nbsp;</FONT></u><br>
micclass=Image<br>html tag=IMG<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
alt=image<SPAN class=passed> (Used</SPAN>, 17 matches)</SPAN><br>image type=Plain Image<SPAN class=passed> (Used</SPAN>, 13 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 13 matches)</SPAN><br>name=Image<SPAN class=passed> (Used</SPAN>, 13 matches)</SPAN><br>file name=search.svg<SPAN class=passed> (Used</SPAN>, 3 matches)</SPAN><br>class=default-img icons-search p-0<SPAN class=passed> (Used</SPAN>, 2 matches)</SPAN><br>visible=-1<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>width=16<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>height=16<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:20]]></Time>
<TimeTick>1751958500</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" MovieMarker="MARK134" >
<Disp><![CDATA["Search_image"- Smart Identification]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf371.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Search_image.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:20]]></Time>
<TimeTick>1751958500</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" MovieMarker="MARK135" >
<Disp><![CDATA[Search_image.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf372.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf370.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="23" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf369.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[Search image Clicked]]></Obj>
<Details ><![CDATA[The search image got clicked]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:20]]></Time>
<TimeTick>1751958500</TimeTick>
<NodeArgs eType="User" icon="8" nRep="28" status="Passed" >
<Disp><![CDATA[Search image Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:21]]></Time>
<TimeTick>1751958501</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:21]]></Time>
<TimeTick>1751958501</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[TITAN.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:21]]></Time>
<TimeTick>1751958501</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" MovieMarker="MARK136" >
<Disp><![CDATA[TITAN.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf375.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf374.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="30" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf373.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Back to home page]]></Obj>
<Details ><![CDATA[Gone back to home page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:21]]></Time>
<TimeTick>1751958501</TimeTick>
<NodeArgs eType="User" icon="8" nRep="33" status="Passed" >
<Disp><![CDATA[Back to home page]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:23]]></Time>
<TimeTick>1751958503</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:24]]></Time>
<TimeTick>1751958504</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Acc_img.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:24]]></Time>
<TimeTick>1751958504</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" MovieMarker="MARK137" >
<Disp><![CDATA[Acc_img.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf378.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf377.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="34" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf376.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj ><![CDATA[Account image exist]]></Obj>
<Details ><![CDATA[Account image exists and working]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:24]]></Time>
<TimeTick>1751958504</TimeTick>
<NodeArgs eType="User" icon="8" nRep="37" status="Passed" >
<Disp><![CDATA[Account image exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[Account image Highlighted]]></Obj>
<Details ><![CDATA[Account image got highlighted]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:26]]></Time>
<TimeTick>1751958506</TimeTick>
<NodeArgs eType="User" icon="8" nRep="38" status="Passed" >
<Disp><![CDATA[Account image Highlighted]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:48]]></Time>
<TimeTick>1751958528</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:48]]></Time>
<TimeTick>1751958528</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA["Account"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:48]]></Time>
<TimeTick>1751958528</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="76" status="Warning" MovieMarker="MARK138" >
<Disp><![CDATA["Account"- Description mismatch]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf381.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA["Account"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>text=Account<br>role=<br>micclass=Link<br>html tag=A<br>acc_name=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (630 objects found)&nbsp;</FONT></u><br>
micclass=Link<br>html tag=A<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
text=Account<SPAN class=Failed> (Skipped)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 115 matches)</SPAN><br>class=px-0 login-menu d-none d-xl-block<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>name=Account<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>href=javascript:void(0)<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:49]]></Time>
<TimeTick>1751958529</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" MovieMarker="MARK139" >
<Disp><![CDATA["Account"- Smart Identification]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf382.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:49]]></Time>
<TimeTick>1751958529</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" MovieMarker="MARK140" >
<Disp><![CDATA[Account.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf383.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="75" status="Warning" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf380.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="74" status="Warning" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf379.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[Account image link clicked]]></Obj>
<Details ><![CDATA[The  account image link got clicked]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:49]]></Time>
<TimeTick>1751958529</TimeTick>
<NodeArgs eType="User" icon="8" nRep="79" status="Passed" >
<Disp><![CDATA[Account image link clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:53]]></Time>
<TimeTick>1751958533</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:53]]></Time>
<TimeTick>1751958533</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[login_desc.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:53]]></Time>
<TimeTick>1751958533</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="82" MovieMarker="MARK141" >
<Disp><![CDATA[login_desc.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf386.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="81" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf385.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="80" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf384.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj ><![CDATA[Login description]]></Obj>
<Details ><![CDATA[The  Login desc exists]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:53]]></Time>
<TimeTick>1751958533</TimeTick>
<NodeArgs eType="User" icon="8" nRep="83" status="Passed" >
<Disp><![CDATA[Login description]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj ><![CDATA[Login description]]></Obj>
<Details ><![CDATA[The  Login desc says:.login-description-head { font-size:16px; line-height: 24px; font-weight: 500; color: #000; margin-top: 26px; margin-bottom:7px; } @media only screen and (min-width: 1024px) { .login-description-head { font-size:20px; line-height: 30px; margin-top: 30px; margin-bottom:7px; } } .login-description-text { font-size:12px; line-height: 18px; font-weight: 400; color: #000; margin-bottom: 0; } @media only screen and (min-width: 1024px) { .login-description-text { font-size:16px; line-height: 24px; margin-bottom:7px; } } Login Please enter your registered mobile number to login via OTP ]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:54]]></Time>
<TimeTick>1751958534</TimeTick>
<NodeArgs eType="User" icon="8" nRep="84" status="Passed" >
<Disp><![CDATA[Login description]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:54]]></Time>
<TimeTick>1751958534</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:54]]></Time>
<TimeTick>1751958534</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[+91.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:54]]></Time>
<TimeTick>1751958534</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="87" MovieMarker="MARK142" >
<Disp><![CDATA[+91.Exist]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf389.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="86" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf388.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="85" >
<Disp><![CDATA[Titan: The Official Website]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf387.xml]]></Path>
<ASHilite><![CDATA[920460]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[Country code element exist]]></Obj>
<Details ><![CDATA[The country code element exists and working]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:54]]></Time>
<TimeTick>1751958534</TimeTick>
<NodeArgs eType="User" icon="8" nRep="88" status="Passed" >
<Disp><![CDATA[Country code element exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj ><![CDATA[Country code element Highlighted]]></Obj>
<Details ><![CDATA[Country code element got Highlighted]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:56]]></Time>
<TimeTick>1751958536</TimeTick>
<NodeArgs eType="User" icon="8" nRep="89" status="Passed" >
<Disp><![CDATA[Country code element Highlighted]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Titan: The Official Website]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[Tue, 08 Jul, 2025 - 12:38:56]]></Time>
<TimeTick>1751958536</TimeTick>
<Step rID="T50">